### ISSUE TITLE
Looking for App.jsx file

### ISSUE THREAD

**Issue by drdexter33** [the-road-to-learn-react/hacker-stories#62]
I can see tsx files, but am not able to see .jsx files.

thanks

**Comment by rwieruch** [comment]
Which link did you click in the book? Can you copy and paste it here?

**Comment by drdexter33** [comment]
I found what I was looking for thanks Robin!!

I forgot that there were links in the book to compare my code against yours in code sandbox..

do you recommend using typescript over javscript?

thanks again...

doug

**Comment by rwieruch** [comment]
Hey Doug, no worries! :) Yes, at the end of each chapter you can either:

- compare your code with my code on CodeSandbox
- check the changes that happened in the chapter on GitHub
- see the TypeScript version of it

React projects these days are mostly using TypeScript, however, I kept the book JavaScript first so that it does not another complexity in learning. If you are not familiar with JS, stick to JS and add TS later :)

**Comment by drdexter33** [comment]
Gotcha..

thanks.
